
ALTER TABLE companies ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS email_support VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS maps_location TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS social_media JSONB DEFAULT '{}';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS logo_url TEXT;
